name: CI Vocabulary Registry

on:
  push:
    branches: [ main, master ]
  pull_request:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pySHACL
        run: |
          python -m pip install --upgrade pip
          pip install pyshacl rdflib

      - name: Validate RDF syntax (TTL) with riot (Docker)
        run: |
          set -e
          if find tems tamis -type f -name "*.ttl" | grep -q .; then
            find tems tamis -type f -name "*.ttl" -print0 \
              | xargs -0 -I{} docker run --rm \
                  -v "$PWD":/rdf -w /rdf \
                  stain/jena riot --validate "{}"
          else
            echo "No .ttl files found; skipping riot validation."
          fi

      - name: SHACL validation
        run: |
          python scripts/validate_shacl.py

      - name: Serialize TTL -> JSON-LD and RDF/XML
        run: |
          bash scripts/serialize.sh

      - name: Prepare site
        run: |
          rm -rf public
          mkdir -p public
          cp -R tems tamis public/
          python scripts/generate_index.py

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        uses: actions/deploy-pages@v4

  release:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bump & Tag (semver minor if ontologies changed)
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: minor
          WITH_V: true
          RELEASE_BRANCHES: main,master
